### ISSUE TITLE
idiomatic way to choose and init sub-config during parsing

### ISSUE THREAD

**Issue by Howuhh** [eladrich/pyrallis#13]
I would like to be able to choose a model config if there are several different models. Example:
```python
# main.py
@dataclass
class Model0Config:
    input_dim: int = 32
    output_dim: int = 32
    hidden_dim: int = 32

@dataclass
class Model1Config:
    input_dim: int = 32
    some_other_arg: str = "test_arg"

class ModelConfigs(Enum):
    model0 = Model0Config
    model1 = Model1Config

@dataclass
class TrainConfig:
    wandb_name: str = "some default name"
    model_config: ModelConfigs = field(default=ModelConfigs.model0)
   
```
Problem here is than I cannot setup sub-config for model is this way, as this will raise an error:
```bash
python main.py --model_config=model1 --model_config.input_dim=128
```
How would you implement something like this? Perhaps there is some other way? Thanks!

**Comment by eladrich** [comment]
Hi @Howuhh, that's a great question and it's actually a pattern we considered when designing pyrallis. Unfortunately, after some thought, we decided that dynamically choosing sub-configs would overcomplicate pyrallis and would be problematic for static analysis of the configuration, and is therefore not supported.

My advice would be to either to go with a slightly different design or check out more advanced configuration libraries such as [hydra](https://hydra.cc/) which might be more suited for such usecases.

As to a pyrallis-compatible design, one can define ModelConfigs as a regular subconfig where each model has it's own set of parameters and possibly put duplicated parameters that have the same initialization values directly in model_config.
```console
python main.py --model_config=model_b --model_config.input_dim=12 --model_config.model_b.some_other_arg=arg_value 
```

**Comment by Howuhh** [comment]
Make sense! Thanks for the answer, I will stick with that design
